### PR TITLE
Funtionalities

### PR DESCRIPTION
**Pull request by Divinity-dev**
1. Added more css styling.
2. Added javascript funtionality

### CODE REVIEW

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Invalid

You have submitted a pair programming project without contribution from all team members. Kindly ensure that all members of the team participate in the project with their commits as evidence.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Divinity-dev** [comment]
My partner isn't available.

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 19, 2023 at 9:26 PM, Emmanuel ***@***.***> wrote:   


@emmiiorji requested changes on this pull request.

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request



You have submitted a pair programming project without contribution from all team members. Kindly ensure that all members of the team participate in the project with their commits as evidence.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers and Happy coding! 👏 👏 👏
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

**Review by Nemwel-Boniface — APPROVED** [review]
## Hello @Divinity-dev          :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 



## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Divinity-dev** [comment]
Thank you.
Sent from Yahoo Mail on Android 
 
  On Fri, Jan 20, 2023 at 9:14 AM, Nemwel ***@***.***> wrote:   


@Nemwel-Boniface approved this pull request.

Hello @Divinity-dev 👋 ,

I am Nemwel your reviewer for this PR 🧔‍♂️
 
Thank you for meeting all the project requirements good job! 🥳
Your project is complete! There is nothing else to say other than... it's time to merge it 
Congratulations! 🥳 🎉
 


Highlights

Great job setting up the correct linters ✔️
Professional documentation ✔️
Correct workflow ✔️
Meaningful commit messages ✔️
Met all the milestone requirements ✔️
 
[Optional] suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding! 👏 👏 👏
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Nemwel-Boniface in your question so I can receive the notification.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

**Pull request merged**
